### PR TITLE
Remove Arrayification of Event's data

### PR DESCRIPTION
**Pull request by diegodurs**
Introducing a breaking change.

With this commit, we restrict aggregate to emit event with only one
object as a payload instead splashing it into an array. 
It seems to reasonnable to not change the payload of emited event. It is confusing, and adds little benefits in terms of feature.

What we loose is the ability to write code like this:

``` ruby
class SomeAggregate
  def on_created(value1, value2)
  end
end

aggregate.emit(:created, value1, value2)
```

Instead we need to transform arguments into an array or an hash like so:

``` ruby
class SomeAggregate
  def on_created(args)
    value1, value2 = *args
  end
end

aggregate.emit(:created, [value1, value2])
```

### CODE REVIEW

**Comment by gregory** [comment]
Ok i think it makes sens. 
What i like, it's that it enforces the fact that any event will always be published with 1 arg. 

Your example is correct, but i'd actually go with the hash instead of the array. (this is personal taste though): 

``` rb
class SomeAggregate
  def on_created(args)
    value1, value2 = args.values_at(:arg1, :arg2)
  end
end

aggregate.emit(:created, { arg1: value1, arg2: value2})
```

With your change, any subscriber can expect to receive events with only one param (the data) and fetch the content that it needs. 

ie: 

``` rb
class Logger
  def log(params={})
    puts params.map{|k,v| "#{k}=#{v}"}.join(', ')
  end
end
```

instead of: 

``` rb
class Logger
  def log(*params)
    #some magic here
  end
end
```

So this is good. 

Before i merge this, could you do me a favor add a spec for this PR to enforce the change we made? 

I should add that to the contributors guideline, but i'd like any API change to be enforce with a spec, beside updating the other specs. 

I'm expecting something like: 

``` rb
# in spec/changes/aggregate_spec.rb
describe Aggregate do
    feature 'PR[pr number] [pr title]' do
    end
end
```

Also, i should do it, but if you can do this before me i'd appreciate if you could add .travis to this project in a separate PR before this one :) 

thx @diegodurs !

**Comment by diegodurs** [comment]
Actually I did some test, but then I had to remove them since they were just contradicting the spec I've modified. So I removed it since it didn't made sense to test twice the expectation on `emit`.
Do you still need a specific PR test ?

I agree on setting a CI but I think you must do it because I do not have moderation access on the repo.

**Comment by gregory** [comment]
will do the CI asap, busy with other stuffs right now. 
I'd like every api change to to be spec'ed to contribute to the change log to help to see why things changed for the user and link that back to the PR number.

Also, if a change spec brakes, it'll be easy to see why that change was made in the past and see if it still makes sens. 

So please, add that test that would demonstrate/enforce the new API (show what we don't want)

**Comment by diegodurs** [comment]
Done, hope it's good enought!

**Comment by gregory** [comment]
[This](https://github.com/gregory/jouba/compare/event-data-transformed-to-array) is more what i was expecting. Note that i rebased from master since i've added travis, changelog and contributing. :)

**Comment by diegodurs** [comment]
It seems like an overkill to add a big feature test. I've added a check that `ArgumentError` was raised if someone tries to emit more than one args.

Note: in your test, the ArgumentError is raised by the method definition of `created` which takes only one argument. It is not Jouba that raises the error. In my test this should be correctly tested.

If you're not happy with this result, please give me **precise** change requests, otherwise we might end up turning around. :)

**Comment by gregory** [comment]
Hey, 
This might seems overkill by comparaison to other gems and contributions you might have seen online, but what i'm trying to achieve here, is transparency and traceability on api changes and bugs.

While in other gems patching the code might just be fine, not only i do want the ability to have a single place where you could see all the changes that happened in context, but i also want the ability to be able to link that change back to the issue discussion on github.

[Before upgrading to newer version]
I want to be able to see how a new feature will affect the way i have been using Jouba's API, and easily be able to load the issue to read the full thread to get more context on why that happened. 
By reading the specs, I will be able to see exactly the braking changes instead of grep-ing in the code and issues, so IMHO it'll be a better experience.

[Enforce API change decisions over time]
The fact we are using specs for that, will also enforce that those decisions will still be valid in time, regarding the eventual implementation changes.

[Make sure bugs wont happened again]
By spec-ing bugs, we'll make sure they wont reproduce again over the time

[Debugging]
After a while, a git blame in the codebase will be enough to link back to issues and API changes (since commit prefixed with issue number), so again IMHO, better experience. 

So here is the precise change requests (i've merged a changelog so read more there if you want more info):
- since this is a feature and not a bug and about Aggregate#emit, please add a spec at `features/jouba/aggregate_spec.rb`
- in the describe, prepend the description with the PR number (this should have been an issue, but since no issue this is fine)
- Please add tests to explicitly show the API change, not the implementation.
- Please change the implementation and fix the failing specs
- Please commit with a message that starts with the PR number (issue number, but since no issue, this is fine) and that explains what changed.
- Please add your line in the changelog

I totally agree that this may look awkward and overkill, but I do want transparency and traceability(btw, this gem is about event sourcing, so you should know the advantages that this will bring) in the code and in the changelog for a better experience.

Feel free to ping me if this is not clear :)

**Comment by gregory** [comment]
btw, @dblock and @krisleech -  i've been doing something similar at work. 
Do you guys think this would be overkill here? 
How do you guys like the idea? 
Thx for input

**Comment by dblock** [comment]
I think what you're asking here is not unreasonable, it's all minor stuff that makes the code look like it was written by 1 person and add tests that clearly demonstrate change.

**Comment by gregory** [comment]
Thanks for your input @dblock - since you've been managing couple popular projects, this input is really valuable :)

**Comment by krisleech** [comment]
Seems okay to me, I maintain the changelog, each PR adds a line to the "unreleased" section. Any items which are breaking are marked clearly so I know if next release needs to bump the major version or not. The API for Wisper is pretty much backwards compatible to version 0, but only because the API is so small, like 4 methods.

If you have good commit messages which are parsable it might be possible to automatically generate the change log, I didn't get this far!

**Comment by gregory** [comment]
awesome, thanks for your input guys!

**Comment by gregory** [comment]
@diegodurs any update? as a reminder, i pushed a quick example here: https://github.com/gregory/jouba/compare/event-data-transformed-to-array

**Pull request closed without merging**
